version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: rust:1.56.0 # 1.56.0 = Rust 2021.
    steps:
      - checkout
      - restore_cache:
          key: registry
      - run: cargo generate-lockfile
      - save_cache:
          key: registry-{{ epoch }}
          paths:
            - ~/.cargo/registry/index
      - restore_cache:
          key: dependencies-1.47-{{ checksum "Cargo.lock" }}
      - run: cargo test
      - save_cache:
          key: dependencies-1.47-{{ checksum "Cargo.lock" }}
          paths:
            - target
            - ~/.cargo/registry/cache
